### ISSUE TITLE
Version for windows?

### ISSUE THREAD

**Issue by LukasLewandowski** [piotrekkmt/chromedriver-appium#2]
Is there a way to use that fixed chromedriver on windows? I need exe file :/

**Comment by piotrekkmt** [comment]
Hi @LukasLewandowski , I found a version I exported on January 22, 2016. Uploaded it to the repo for you. No guarantee it will work at all since it wasn't tested with today's apps or today's version of Chrome but do give it a go and see if it's any good. I don't have the setup anymore but if you're willing, the steps I took to recreate it are in the README. You'd have the advantage of using the current version of Chromium and possibly compiling for Windows on Windows.

**Comment by LukasLewandowski** [comment]
Unfortunately, that version is not working correctly with Windows :/
It throws:
"unknown error: cannot parse capability: chromeOptions"

Looking forward to Your instructions how to compile fresh version on Windows machine :)

**Comment by oldsku11** [comment]
It works for me. Thank you very much!

**Comment by LukasLewandowski** [comment]
Sorry my bad, I confirm that version for Windows is working correctly :)

(I have to remove chromeOptions from my desired_cabs)

**Comment by piotrekkmt** [comment]
That's great to hear! Glad I could help.
